version = "1.0"

################################################################################
#### ABOUT PANELS
################################################################################

[main]

name.fr = "Configuration de Paheko"

    ############################################################################
    #### ABOUT SECTIONS
    ############################################################################

    [main.smtp]
    name = "Configuration SMTP"
    optional = false

        [main.smtp.smtp_host]
            ask.fr = "Serveur SMTP"
            type = "string"
            bind = "SMTP_HOST:__INSTALL_DIR__/config.local.php"

        [main.smtp.smtp_port]
            ask.fr = "Port"
            min = 25
            type = "number"
            bind = "SMTP_PORT:__INSTALL_DIR__/config.local.php"

        [main.smtp.smtp_user]
            ask.fr = "Nom d'utilisateur"
            type = "string"
            bind = "SMTP_USER:__INSTALL_DIR__/config.local.php"

        [main.smtp.smtp_password]
            ask.fr = "Mot de passe"
            type = "password"
            bind = "SMTP_PASSWORD:__INSTALL_DIR__/config.local.php"

        [main.smtp.smtp_security]
            ask.fr = "Sécurité de la connexion"
            type = "select"
            choices.NONE = "NONE, pas de chiffrement"
            choices.SSL = "SSL, connexion SSL native"
            choices.TLS = "TLS, connexion TLS native (le plus sécurisé)"
            choices.STARTTLS = "STARTTLS, utilisation de STARTTLS (moyennement sécurisé)"
            bind = "SMTP_SECURITY:__INSTALL_DIR__/config.local.php"

        [main.smtp.mail_sender]
            ask.fr = "Adresse e-mail expéditrice des messages"
            type = "string"
            bind = "MAIL_SENDER:__INSTALL_DIR__/config.local.php"

        [main.smtp.mail_return_path]
            ask.fr = "Adresse e-mail expéditrice des messages"
            type = "string"
            bind = "MAIL_RETURN_PATH:__INSTALL_DIR__/config.local.php"

    [main.system_signal]
    name = "Ajouts des utilisateurs de Paheko dans Yunohost"
    optional = true

        [main.system_signal.enable_system_signal]
        ask.fr = "Configurer l'ajout des utilisateurs de Paheko dans Yunohost ?"
        type = "boolean"
        help.fr = "Corresponds à un mécanisme qui permet d'envoyer des signaux à Yunohost pour créer des utilisateurs Yunohost depuis Paheko."
