version = "1.0"

################################################################################
#### ABOUT PANELS
################################################################################

[main]

name.fr = "Configuration de Paheko"

    ############################################################################
    #### ABOUT SECTIONS
    ############################################################################

    [main.smtp]

    name = "Configuration SMTP"

    ## (optional) This help properties is a short help displayed on the same line

    optional = false

    [main.smtp.smtp_host]
        ask = "Serveur SMTP"
        type = "string"
        bind = "SMTP_HOST:__INSTALL_DIR__/config.local.php"

    [main.smtp.smtp_port]
        ask = "Port"
        min = 25
        type = "number"
        bind = "SMTP_PORT:__INSTALL_DIR__/config.local.php"

    [main.smtp.smtp_user]
        ask = "Nom d'utilisateur"
        type = "string"
        bind = "SMTP_USER:__INSTALL_DIR__/config.local.php"

    [main.smtp.smtp_password]
        ask = "Mot de passe"
        type = "password"
        bind = "SMTP_PASSWORD:__INSTALL_DIR__/config.local.php"

    [main.smtp.smtp_security]
        ask = "Sécurité de la connexion"
        type = "select"
        choices.NONE = "NONE, pas de chiffrement"
        choices.SSL = "SSL, connexion SSL native"
        choices.TLS = "TLS, connexion TLS native (le plus sécurisé)"
        choices.STARTTLS = "STARTTLS, utilisation de STARTTLS (moyennement sécurisé)"
        bind = "SMTP_SECURITY:__INSTALL_DIR__/config.local.php"

    [main.smtp.mail_sender]
        ask = "Adresse e-mail expéditrice des messages"
        type = "string"
        bind = "MAIL_SENDER:__INSTALL_DIR__/config.local.php"

    [main.smtp.mail_return_path]
        ask = "Adresse e-mail de réponse des messages"
        type = "string"
        bind = "MAIL_RETURN_PATH:__INSTALL_DIR__/config.local.php"

