test_format = 1.0

[default]


    # -------------------------------
    # Default args to use for install
    # -------------------------------
    args.country = "FR"
    args.name_association = "Mon Association"
    args.user_name = "Agathe Afeeling"
    args.user_email = "a.afeeling@example.com"
    args.password = "Foutu Mémoire Adieu Distance Corneille"


    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e2ebdf9a82f868bed14fae4d24542b04fd6f46b9.name = "Upgrade from 1.3.0"
    test_upgrade_from.e2ebdf9a82f868bed14fae4d24542b04fd6f46b9.args.domain = "domain.tld"
    test_upgrade_from.e2ebdf9a82f868bed14fae4d24542b04fd6f46b9.args.path = "/paheko"
