test_format = 1.0

[default]


    # -------------------------------
    # Default args to use for install
    # -------------------------------
    args.country = "FR"
    args.name_association = "Mon Association"
    args.user_name = "Agathe Afeeling"
    args.user_email = "a.afeeling@example.com"
    args.password = "Foutu Mémoire Adieu Distance Corneille"


    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.534bb03f927c5301e69bc0339a7441142a75b485.name = "Upgrade from 1.2.8"
    test_upgrade_from.534bb03f927c5301e69bc0339a7441142a75b485.args.domain = "domain.tld"
    test_upgrade_from.534bb03f927c5301e69bc0339a7441142a75b485.args.path = "/paheko"
