test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e2ebdf9a82f868bed14fae4d24542b04fd6f46b9.name = "Upgrade from 1.3.0"
    test_upgrade_from.e2ebdf9a82f868bed14fae4d24542b04fd6f46b9.args.domain = "domain.tld"
    test_upgrade_from.e2ebdf9a82f868bed14fae4d24542b04fd6f46b9.args.path = "/paheko"
