#!/usr/bin/bash
user="$1"
user_info=$(yunohost user info "$user" --json)
app="paheko"
if yunohost user permission info "$app" --json |jq -r ".corresponding_users[]" | grep -q "^$user$" ; then
	id_user_paheko=$(sqlite3 /home/yunohost.app/paheko/data/association.sqlite "select id from users where ynh_username='$YNH_USER_USERNAME'")
	# Création d'un user
	BODY='--------------------------pahekoform
Content-Disposition: form-data; name="ynh_username"

'$user'
'
YNH_USER_LASTNAME=$(echo "$user_info" |jq -r ".fullname")
	if [[ -n "$YNH_USER_LASTNAME" ]]; then
		BODY+='--------------------------pahekoform
Content-Disposition: form-data; name="nom"

'$YNH_USER_LASTNAME'
'
	fi
YNH_USER_FIRSTNAME=$(echo "$user_info" |jq -r ".fullname")
	if [[ -n "$YNH_USER_FIRSTNAME" ]]; then
		BODY+='--------------------------pahekoform
Content-Disposition: form-data; name="prenom"

'$YNH_USER_FIRSTNAME'
'
	fi
	mail=$(echo "$user_info"| jq -r '.["mail-forward"][]' |head -n1)
	if [[ -z "$mail" ]]; then
		mail=$(echo "$user_info" | jq -r '.mail' |head -n1)
	fi
	if [[ -n "$mail" ]]; then
		BODY+='--------------------------pahekoform
Content-Disposition: form-data; name="email"

'$mail'
'
	fi

	BODY+='--------------------------pahekoform--'

#--------------------------pahekoform
#Content-Disposition: form-data; name="statut"
#
#chomeur-euse
#--------------------------pahekoform
#Content-Disposition: form-data; name="montant_cotisation"
#
#O
#--------------------------pahekoform
#Content-Disposition: form-data; name="mode_reglement"
#
#virement
#--------------------------pahekoform
#Content-Disposition: form-data; name="engagement_valeurs"
#
#true
#--------------------------pahekoform
#Content-Disposition: form-data; name="password"
#
#blabla@75232156767986867
	if [[ "$id_user_paheko" == "" ]]; then
		id_user_paheko="new"
	fi
        printf '%s' "$BODY" | \
        SCRIPT_FILENAME=/var/www/paheko/www/_route.php \
        REQUEST_METHOD=POST \
        REQUEST_URI=/api/user/$id_user_paheko \
        CONTENT_TYPE='multipart/form-data; boundary=------------------------pahekoform' \
        CONTENT_LENGTH="$(printf '%s' "$BODY" | wc -c)" \
        PHP_AUTH_USER='ynh_user_hook' \
        PHP_AUTH_PW='jdpjyDJwf9XkquK31JrUYw' \
        cgi-fcgi -bind -connect /var/run/php/php8.5-fpm-paheko.sock
fi
