#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

secret_key=$(ynh_string_random --length=50)
ynh_app_setting_set --app="$app" --key=secret_key --value="$secret_key"

smtp_host=$domain
smtp_port=25
smtp_user=$app
smtp_password=$mail_pwd
smtp_security=STARTTLS
mail_return_path=$app@$domain
mail_sender=$app@$domain
ynh_app_setting_set --app="$app" --key=smtp_host --value="$smtp_host"
ynh_app_setting_set --app="$app" --key=smtp_port --value="$smtp_port"
ynh_app_setting_set --app="$app" --key=smtp_user --value="$smtp_user"
ynh_app_setting_set --app="$app" --key=smtp_password --value="$smtp_password"
ynh_app_setting_set --app="$app" --key=smtp_security --value="$smtp_security"
ynh_app_setting_set --app="$app" --key=mail_return_path --value="$mail_return_path"
ynh_app_setting_set --app="$app" --key=mail_sender --value="$mail_sender"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=4

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir" "$data_dir"
chmod -R u=rX,g=rX,o= "$install_dir"
chmod -R g+rX "$install_dir/www"
chmod -R u+wX "$install_dir/data" "$data_dir"
# from https://fossil.kd2.org/paheko/wiki?name=Configuration/S%C3%A9curit%C3%A9

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

# Create a dedicated NGINX config
ynh_add_nginx_config

ynh_add_config --template="cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATIONS
#=================================================
ynh_script_progression --message="Adding configuration files..." --weight=5

# Install configuration files

ynh_add_config --template="config.local.user.php" --destination="$data_dir/data/config.local.user.php"

chmod 640 "$data_dir/data/config.local.user.php"
chown $app:$app "$data_dir/data/config.local.user.php"

ynh_add_config --template="config.local.php" --destination="$install_dir/config.local.php"

chmod 440 "$install_dir/config.local.php"
chown "$app:$app" "$install_dir/config.local.php"

ynh_script_progression --message="Adding a configuration directory..." --weight=5

if [ ! -d "$data_dir/data/local_addresses" ]; then
mkdir "$data_dir/data/local_addresses"
chmod 770 "$data_dir/data/local_addresses"
chown -R $app:www-data "$data_dir/data/local_addresses"
fi

#=================================================
# SETUP APPLICATION
#=================================================

### Waiting for new script  which will be integrated in version 1.3.12 see https://fossil.kd2.org/paheko/wiki?name=Ligne+de+commande

# Post-Installation
ynh_script_progression --message="Finalizing Post-installation..." --weight=1

country=$country
name_association=$name_association
user_name=$user_name
user_email=$user_email
password=$password

ynh_exec_as $app php$phpversion $install_dir/bin/paheko init --country $country --orgname '$name_association' --name='$user_name' --email='$user_email' --password='$password'

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
