#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=5

ynh_restore_file --origin_path="$install_dir"

# Restore permissions on app files
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
find "$install_dir" -type d -exec chmod 550 {} +
find "$install_dir" -type f -exec chmod 440 {} +
find "$install_dir/data" -type d -exec chmod 770 {} +
find "$install_dir/data" -type f -exec chmod 660 {} +
chmod 440 "$install_dir/config.local.php"
chmod 440 "$install_dir/config.local.yunohost.php"

if [[ $install_dir/config.local.user.php -f ]]; then
chmod 660 $install_dir/config.local.user.php
else
chmod 660 "$install_dir/data/config.local.user.php"
fi

#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring the PHP-FPM configuration..." --weight=6

ynh_restore_file --origin_path="/etc/php/$phpversion/fpm/pool.d/$app.conf"

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring the NGINX web server configuration..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression --message="Reloading NGINX web server and PHP-FPM..." --weight=1

ynh_systemd_action --service_name=php$phpversion-fpm --action=reload
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
